#!/bin/bash
# ############################################################################################
# File: ........: pcfconfig-pks-harbor
# Language .....: bash
# Author .......: Sacha Dubois, Pivotal
# Description ..: PCF OpsManager Configuration Utility
# ############################################################################################

if [ "${1}" == "" ]; then
  echo "$0 <env-file>"; exit 0
fi

envFile=$1

export PCFCONFIG_BASE=$(basename $0)
export PCFPATH=$HOME/pcfconfig

# --- SOURCE FUNCTIONS---
. ${PCFPATH}/functions
. $envFile

messageTitle "Install Harbor"
messagePrint " - Harbor Version:"                  "$PCF_TILE_HARBOR_VERSION"
messagePrint " - Tile Config:"                     "$PCF_TILE_HARBOR_CONFIG"
messagePrint " - Stemcell Type:"                   "$PCF_TILE_HARBOR_STEMCELL_TYPE"
messagePrint " - Stemcell Version:"                "$PCF_TILE_HARBOR_STEMCELL_VERSION"

#PCF_TILE_HARBOR_DEPLOY=true
#PCF_TILE_HARBOR_NAME=harbor-container-registry
#PCF_TILE_HARBOR_VERSION=1.8.3
#PCF_TILE_HARBOR_BUILD=1.8.3-build.2
#PCF_TILE_HARBOR_CONFIG=harbor_azure_1.8.yml
#PCF_TILE_HARBOR_STEMCELL_TYPE=stemcells-ubuntu-xenial
#PCF_TILE_HARBOR_STEMCELL_VERSION=250.25


exit 1
