#!/bin/bash
# ############################################################################################
# File: ........: pcfconfig-pks-harbor
# Language .....: bash
# Author .......: Sacha Dubois, Pivotal
# Description ..: PCF OpsManager Configuration Utility
# ############################################################################################

if [ "${1}" == "" ]; then
  echo "$0 <env-file>"; exit 0
fi

envFile=$1

export PCFCONFIG_BASE=$(basename $0)
export PCFPATH=$HOME/pcfconfig

# --- SOURCE FUNCTIONS---
. ${PCFPATH}/functions
. $envFile

# --- CHECK UTILITIES ---
checkOpsMantools

echo "OM:$OM"

messageTitle "Install Harbor"
messagePrint " - Harbor Version:"                  "$PCF_TILE_HARBOR_VERSION"
messagePrint " - Harbor Slug:"                     "$PCF_TILE_HARBOR_NAME"
messagePrint " - Tile Config:"                     "$PCF_TILE_HARBOR_CONFIG"
messagePrint " - Stemcell Type:"                   "$PCF_TILE_HARBOR_STEMCELL_TYPE"
messagePrint " - Stemcell Version:"                "$PCF_TILE_HARBOR_STEMCELL_VERSION"

HARBOR_SLUG=$PCF_TILE_HARBOR_NAME
HARBOR_VERSION=$PCF_TILE_HARBOR_VERSION

  OPS_MANAGER_URL="pcf.${PCF_DEPLOYMENT_ENV_NAME}.${AWS_HOSTED_DNS_DOMAIN}"
  OM_LOGIN="--skip-ssl-validation --target ${OPS_MANAGER_URL} --username $PCF_OPSMANAGER_ADMIN_USER \
            --password $PCF_OPSMANAGER_ADMIN_PASS"

uploadProductTile $PCF_TILE_HARBOR_NAME $PCF_TILE_HARBOR_VERSION
uploadStemCell    $PCF_TILE_HARBOR_STEMCELL_TYPE $PCF_TILE_HARBOR_STEMCELL_VERSION


exit 1
