#!/bin/bash
# ############################################################################################
# File: ........: pcfconfig
# Language .....: bash
# Author .......: Sacha Dubois, Pivotal
# Description ..: PCF Installation and Configuration Utility
# ############################################################################################

export PATH=~/workspace/pcfconfig:~/pcfconfig:$PATH

PCFCONFIG_PATH=$(dirname $0)
PCFCONFIG_BASE=$(basename $0)

# --- SOURCE FUNCTIONS---
. ${PCFCONFIG_PATH}/functions

DEBUG=0
PIVNET_TOKEN=""
ROUTE53_TOKEN=""
OPSMAN_USER=""
OPSMAN_PASS=""
OPSMAN_DKEY=""
PCF_VERSION=""
PKS_VERSION=""
PKS_CLUSTER_1_NAME=""
PKS_CLUSTER_1_PLAN=""
PKS_CLUSTER_2_NAME=""
PKS_CLUSTER_2_PLAN=""
PKS_CLUSTER_3_NAME=""
PKS_CLUSTER_3_PLAN=""

PAS_VERSION=""
PKS_ADMIN_USER=""
PKS_ADMIN_PASS=""
PKS_ADMIN_MAIL=""
PAS_SRT=""
DNS_DOMAIN=""
TF_WORKDIR="$(dirname ~/workspace)/$(basename ~/workspace)"

AZURE_SUBSCRIPTION_ID=""
AZURE_TENANT_ID=""
AZURE_CLIENT_ID==
AZURE_CLIENT_SECRET=""
AZURE_LOCATION=""
AWS_ACCESS_KEY=""
AWS_SECRET_KEY=""
AWS_REGION=""
GCP_SERVICE_ACCOUNT=""
GCP_PROJECT=""
GCP_REGION=""
GCP_PROJECT=""
CLOUD_PROVIDER=""
PRODUCT_TILE=""
JUMP_SERVER=0

usage() {
  echo "USAGE: $PCFCONFIG_BASE [options]"
  echo "             Configuration Settings"
  echo "                       --jump-server                    - Use a jump Server"
  echo "                       --admin-user <login>             - OpsManager Admin User"
  echo "                       --admin-pass <password>          - OpsManager Admin Password"
  echo "                       --decryption-key <phrase>        - OpsManager Decryption Prhase"
  echo "                       --pivnet-token <token>           - Pivnet API Token"
  echo "                       --workdir <directory>            - Working Directory (default: ~/workspace)"
  echo "                       --env-name <name>                - Environment Name"
  echo "                       --dns-domain <vars>              - DNS Domain Name"
  echo "                       --aws-route53 <token>            - AWS Route53 Token"
  echo ""
  echo "             Product Settings>"
  echo "                       --pks-version <version>          - PKS Version"
  echo "                       --pks-admin-user <user>          - PKS Administration User"
  echo "                       --pas-admin-pass <password>      - PKS Administration Password"
  echo "                       --pas-admin-mail <email>         - PKS Administration Email"
  echo "                       --pas-version <version>          - PAS Version"
  echo "                       --pas-srt                        - PAS Small Footprint"
  echo "                       --harbor-version <version>       - PAS Version"
  echo ""
  echo "             Google Cloud Platform (GCP)"
  echo "                       --gcp-service-account <file>     - GCP Access Key"
  echo "                       --gcp-region <val>               - GCP Region  (gcloud projects list)"
  echo "                       --gcp-project-name <val>         - GCP Project (gcloud compute zones list)"
  echo ""
  echo "             Microsoft Azure Cloud (Azure)"
  echo "                       --azure-subscription_id <val>    - Azure Subscription Id"
  echo "                       --azure-tenant_id <val>          - Azure Tenant Id"
  echo "                       --azure-client_id <val>          - Azure Client/Application Id"
  echo "                       --azure-client_secret            - Azure Client Secret"
  echo "                       --azure-location <val>           - Azure Location"
  echo ""
  echo "             Amazon Web Services (AWS)"
  echo "                       --aws-access_key <val>           - AWS Access Key"
  echo "                       --aws-secret_key <val>           - AWS Secret Key"
  echo "                       --aws-region <val>               - AWS Region"
  echo ""
}

if [ "${1}" == "" ]; then 
  usage; exit 0
fi

CMDLINE_ARGS=$(echo "$*" | sed -e 's/--jump-server//g' -e 's/ - / "-" /g' -e 's/ -$/ "-" /g') 
echo "`hostname` CMDLINE_ARGS:$CMDLINE_ARGS"
echo "`hostname` 1:$1"
echo "`hostname` *:$*"

while [ "$1" != "" ]; do
echo "- $1"
  case $1 in
    --debug) DEBUG=1;; 
    --usage) USAGE=1;;
    --jump-server) JUMP_SERVER=1;;
    --pas-srt ) PAS_SRT="--pas-srt";;
    --gcp-service-account) GCP_SERVICE_ACCOUNT=$2; shift;;       # GCP SERVICE_ACCOUNT
    --gcp-project) GCP_PROJECT=$2; shift;;       # GCP PROJECT
    --pivnet-token) PIVNET_TOKEN=$2; shift;;                     # PCFCONFIG-PKS
    --pks-version) PKS_VERSION=$2; shift;;                       # TERRAFORM VARIABLE FILE
    --pas-version) PAS_VERSION=$2; shift;;                       # TERRAFORM VARIABLE FILE
    --pks-admin-user) PKS_ADMIN_USER=$2; shift;;              # PCFCONFIG-PKS
    --pks-admin-pass) PKS_ADMIN_PASS=$2; shift;;                # PCFCONFIG-PKS
    --pks-admin-mail) PKS_ADMIN_MAIL=$2; shift;;                # PCFCONFIG-PKS
    --pks-cluster-1-name) PKS_CLUSTER_1_NAME=$2; shift;;
    --pks-cluster-1-plan) PKS_CLUSTER_1_PLAN=$2; shift;;
    --pks-cluster-2-name) PKS_CLUSTER_2_NAME=$2; shift;;
    --pks-cluster-2-plan) PKS_CLUSTER_2_PLAN=$2; shift;;
    --pks-cluster-3-name) PKS_CLUSTER_3_NAME=$2; shift;;
    --pks-cluster-3-plan) PKS_CLUSTER_3_PLAN=$2; shift;;
    --aws-route53) ROUTE53_TOKEN=$2; shift;;                     # TERRAFORM VARIABLE FILE
    --pivnet-token) PIVNET_TOKEN=$2; shift;;                     # PCFCONFIG-PKS
    --admin-user) OPSMAN_USER=$2; shift;;                        # PCFCONFIG-OPSMAN / PCFCONFIG-PKS/PAS
    --admin-pass) OPSMAN_PASS=$2; shift;;                        # PCFCONFIG-OPSMAN / PCFCONFIG-PKS/PAS
    --decryption-key) OPSMAN_DKEY=$2; shift;;                    # PCFCONFIG-OPSMAN
    --azure-subscription_id) AZURE_SUBSCRIPTION_ID=$2; shift;;   # PCFCONFIG-OPSMAN
    --azure-tenant_id) AZURE_TENANT_ID=$2; shift;;               # PCFCONFIG-OPSMAN
    --azure-client_id) AZURE_CLIENT_ID=$2; shift;;               # PCFCONFIG-OPSMAN
    --azure-client_secret) AZURE_CLIENT_SECRET=$2; shift;;       # PCFCONFIG-OPSMAN
    --azure-location) AZURE_LOCATION=$2; shift;;                 # AWS LOCATION
    --aws-access_key) AWS_ACCESS_KEY=$2; shift;;                 # AWS ACCESS KEY
    --aws-secret_key) AWS_SECRET_KEY=$2; shift;;                 # AWS SECRET KEY
    --gcp-region) GCP_REGION=$2; shift;;                         # PCFCONFIG-OPSMAN
    --gcp-project-name) GCP_PROJECT=$2; shift;;                  # PCFCONFIG-OPSMAN
    --azure-location) AWSSECRETKEY=$2; shift;;                   # PCFCONFIG-OPSMAN
    --aws-region) AWS_REGION=$2; shift;;                         # PCFCONFIG-OPSMAN
    --dns-domain) DNS_DOMAIN=$2; shift;;                         # PCFCONFIG-OPSMAN
    --env-name) ENV_NAME=$2; shift;;                             # PCFCONFIG-OPSMAN
    --workdir) TF_WORKDIR=$2; shift;;                            # PCFCONFIG-OPSMAN
  esac
  shift
done

echo "AZURE_SUBSCRIPTION_ID:$AZURE_SUBSCRIPTION_ID"
echo "AWS_ACCESS_KEY:$AWS_ACCESS_KEY"
echo "GCP_SERVICE_ACCOUNT:$GCP_SERVICE_ACCOUNT"

# --- CHECK CLOUD CREDENTIALS ---
if [ "${AZURE_SUBSCRIPTION_ID}" == "" -a "${AWS_ACCESS_KEY}" == "" -a "${GCP_SERVICE_ACCOUNT}" == "" ]; then
  echo "ERROR: Either Azure, AWS or GCP credentials needs to be provided"; exit 1
fi

# --- CHECK FOR AZURE ---
if [ "${AZURE_SUBSCRIPTION_ID}" != "" ]; then
  if [ "${CLOUD_PROVIDER}" != "" ]; then 
    echo "ERROR: Please provide only the credentials of the Cloud Environment you want to deploy"; exit 1
  else 
    CLOUD_PROVIDER="azure"
  fi
fi

# --- CHECK FOR AWS ---
if [ "${AWS_ACCESS_KEY}" != "" ]; then
  if [ "${CLOUD_PROVIDER}" != "" ]; then 
    echo "ERROR: Please provide only the credentials of the Cloud Environment you want to deploy"; exit 1
  else 
    CLOUD_PROVIDER="aws"
  fi
fi

# --- CHECK FOR GCP ---
if [ "${GCP_SERVICE_ACCOUNT}" != "" ]; then
  if [ "${CLOUD_PROVIDER}" != "" ]; then 
    echo "ERROR: Please provide only the credentials of the Cloud Environment you want to deploy"; exit 1
  else 
    CLOUD_PROVIDER="gcp"
  fi
fi

if [ ${JUMP_SERVER} -eq 1 ]; then
echo "########### JUMP SERVER ############"
  echo ""
  echo "PCF Configuration Utility ($PCFCONFIG_BASE)"
  echo "by Sacha Dubois, Pivotal Inc,"
  echo "-----------------------------------------------------------------------------------------------------------"
  TF_DEPLOYMENT=$CLOUD_PROVIDER
  JUMP_HOST="jump-${ENV_NAME}.${DNS_DOMAIN}"

  checkCloudCLI
  checkOpsMantools
  installJumpHost

  if [ "${CLOUD_PROVIDER}" == "aws" ]; then
    sed -in "/$JUMP_HOST/d" ~/.ssh/known_hosts
    echo "ssh -qo StrictHostKeyChecking=no -i ~/.ssh/pcfjump.awspas.pcfsdu.com.pem ec2-user@$JUMP_HOST"
    echo "ssh -qo StrictHostKeyChecking=no -i ~/.ssh/${JUMP_HOST}.pem ubuntu@$JUMP_HOST"

    # --- INSTALL SOFTWARE ---
    SSHPAR="-qo StrictHostKeyChecking=no -o ConnectTimeout=5 -i ~/.ssh/${JUMP_HOST}.pem ubuntu@$JUMP_HOST"
    GITPCF="https://github.com/pivotal-sadubois/pcfconfig.git"
    PCFHOME="/home/ubuntu/pcfconfig"

    ret=1
    while [ $ret -ne 0 ]; do
      ssh ${SSHPAR} -n id > /dev/null 2>&1; ret=$?
      [ $ret -ne 0 ] && sleep 10
    done

    echo "------------------------------ CLONE / UPDATE PCFCONFIG GIT RPOSITORY -------------------------------------"
    ssh ${SSHPAR} -n "[ ! -d /home/ubuntu/pcfconfig ] && git clone $GITPCF"
    ssh ${SSHPAR} -n "[ -d /home/ubuntu/pcfconfig ] && cd $PCFHOME; git pull"

    # --- TEST FOR RUNNING REMOTE SCRIPT ---
    stt=$(ssh ${SSHPAR} -n "[ -f /tmp/pcfconfig.pid ] && pgrep -F /tmp/pcfconfig.pid")
    stt=$(ssh ${SSHPAR} -n "[ -f /jump_software_installed ] && echo true")
    if [ "${stt}" == "" ]; then 
      echo "----------------------------------------- INSTALL SOFTWARE ------------------------------------------------"
      ssh ${SSHPAR} -n "[ -d /home/ubuntu/pcfconfig ] && chmod a+x ${PCFHOME}/scripts/jumpInstallUtilities.sh && \
          nohup sudo ${PCFHOME}/scripts/jumpInstallUtilities.sh $PIVNET_TOKEN" 
      echo "-----------------------------------------------------------------------------------------------------------"
      scp -rqo StrictHostKeyChecking=no -i ~/.ssh/${JUMP_HOST}.pem ~/.aws ubuntu@$JUMP_HOST:/home/ubuntu
    fi

    ssh ${SSHPAR} -n "~/pcfconfig/pcfconfig.sh $CMDLINE_ARGS"
    #ssh ${SSHPAR} -n "nohup /home/ubuntu/pcfconfig/pcfconfig $CMDLINE_ARGS"
    #ssh ${SSHPAR} -n "/home/ubuntu/pcfconfig/pcfconfig $CMDLINE_ARGS"
  fi

  if [ "${CLOUD_PROVIDER}" == "gcp" ]; then 
    GITPCF="https://github.com/pivotal-sadubois/pcfconfig.git"
    PCFHOME="~/pcfconfig"
    ZONE=$(gcloud compute zones list | grep " $GCP_REGION " | head -1 | awk '{ print $1 }')

    ret=1
    while [ $ret -ne 0 ]; do
      gcloud compute ssh --zone=$ZONE pcfjump -- hostname > /dev/null 2>&1; ret=$?
      [ $ret -ne 0 ] && sleep 10
    done

    GCPSVC=$(echo $GCP_SERVICE_ACCOUNT | awk -F'/' '{ print $NF }') 
    GCPPTH=$(dirname $GCP_SERVICE_ACCOUNT) 

    echo "------------------------------ CLONE / UPDATE PCFCONFIG GIT RPOSITORY -------------------------------------"
    gcloud compute ssh --zone=$ZONE pcfjump -- "[ ! -d ~/pcfconfig ] && git clone $GITPCF" 2>/dev/null
    gcloud compute ssh --zone=$ZONE pcfjump -- "[ -d ~/pcfconfig ] && cd $PCFHOME; git pull" 2>/dev/null
    stt=$(gcloud compute ssh --zone=$ZONE pcfjump -- "[ -f /jump_software_installed ] && echo true" 2>/dev/null)
    if [ "${stt}" == "" ]; then
      echo "----------------------------------------- INSTALL SOFTWARE ------------------------------------------------"
      gcloud compute ssh --zone=$ZONE pcfjump -- "[ -d ~/pcfconfig ] && chmod a+x ${PCFHOME}/scripts/jumpInstallUtilities.sh && \
          sudo ${PCFHOME}/scripts/jumpInstallUtilities.sh $PIVNET_TOKEN" 2>/dev/null

      # --- COPY AWS CREDENTIALS FOR ROUTE53 ---
      gcloud compute scp --zone=$ZONE --recurse ~/.aws pcfjump:~/ > /dev/null 2>&1

      echo "------------------------------------ ACTIVATE GCP_SERVICE_ACCOUNT -------------------------------------------"
      gcloud compute scp --zone=$ZONE $GCP_SERVICE_ACCOUNT pcfjump:/tmp/$GCPSVC > /dev/null 2>&1
      gcloud compute scp --zone=$ZONE $GCP_SERVICE_ACCOUNT pcfjump:~/$GCPSVC > /dev/null 2>&1
      gcloud compute ssh --zone=$ZONE pcfjump -- gcloud auth activate-service-account --quiet \
            --key-file=/tmp/toolsmith-pa-sadubois-4ecf9e2c-448c4c2bb547.json 2>/dev/null
      echo "-----------------------------------------------------------------------------------------------------------"
    fi

echo "CMDLINE_ARGS:$CMDLINE_ARGS"
exit 1
    gcloud compute ssh --zone=$ZONE pcfjump -- "~/pcfconfig/pcfconfig.sh $CMDLINE_ARGS --gcp-service-account ~/$GCPSVC"

    #ssh ${SSHPAR} -n "~/pcfconfig/pcfconfig.sh $CMDLINE_ARGS"
  fi

  exit 1
fi 


# --- CHECK PRODUCT SELECTION ---
if [ "${PKS_VERSION}" == "" -a "${PAS_VERSION}" == "" ]; then
  echo "ERROR: Either PKS or PAS Version needs to be provided"; exit 1
fi

# --- CHECK PRODUCT SELECTION ---
if [ "${PKS_VERSION}" != "" ]; then 
  if [ "${PAS_VERSION}" != "" ]; then
    echo "ERROR: Only one product can be deployed at a time, please provide the PKS or PAS Version"; exit 1
  else
    PRODUCT_TILE=pks
    PRODUCT_TILE_NAME=PKS
    PCF_VERSION=$PKS_VERSION
    TF_TILE_OPTION="--pks-tfvars"
  fi
else
  PRODUCT_TILE=pas
  PRODUCT_TILE_NAME=PAS
  PCF_VERSION=$PAS_VERSION
  TF_TILE_OPTION="--pas-tfvars"
fi

if [ $DEBUG -gt 0 ]; then 
  echo "PIVNET_TOKEN:$PIVNET_TOKEN"
  echo "ROUTE53_TOKEN:$ROUTE53_TOKEN"
  echo "OPSMAN_USER:$OPSMAN_USER"
  echo "OPSMAN_PASS:$OPSMAN_PASS"
  echo "OPSMAN_DKEY:$OPSMAN_DKEY"
  echo "PKS_VERSION:$PKS_VERSION"
  echo "PAS_VERSION:$PAS_VERSION"
  echo "AZURE_SUBSCRIPTION_ID:$AZURE_SUBSCRIPTION_ID"
  echo "AZURE_TENANT_ID:$AZURE_TENANT_ID"
  echo "AZURE_CLIENT_ID:$AZURE_CLIENT_ID"
  echo "AZURE_CLIENT_SECRET:$AZURE_CLIENT_SECRET"
  echo "AZURE_LOCATION:$AZURE_LOCATION"
  echo "AWS_ACCESS_KEY:$AWS_ACCESS_KEY"
  echo "AWS_SECRET_KEY:$AWS_SECRET_KEY"
  echo "AWS_REGION:$AWS_REGION"
  echo "DNS_DOMAIN:$DNS_DOMAIN"
  echo "CLOUD_PROVIDER:$CLOUD_PROVIDER"
  echo "PRODUCT_TILE:$PRODUCT_TILE"
fi

echo ""
echo "PCF Configuration Utility ($PCFCONFIG_BASE)"
echo "by Sacha Dubois, Pivotal Inc,"
echo "-----------------------------------------------------------------------------------------------------------"
TF_DEPLOYMENT=$CLOUD_PROVIDER
checkCloudCLI
checkOpsMantools

# --- VERIFY PRODUCT VERSION ---
if [ "$PRODUCT_TILE" == "pks" ]; then 
  PCF_RELEASE_NOTES=${PCFCONFIG_PATH}/files/opsman-pks-release-notes.txt
else
  PCF_RELEASE_NOTES=${PCFCONFIG_PATH}/files/opsman-pas-release-notes.txt
fi

cnt=$(echo $PCF_VERSION | awk -F'.' '{ print NF }')
if [ ${cnt} -ne 3 ]; then
  echo "ERROR: $PRODUCT_TILE_NAME Version ($PCF_VERSION) should be in the format x.y.z"; exit 1
fi

if [ -f ${PCF_RELEASE_NOTES} ]; then 
  cnt=$(egrep -c "^${PCF_VERSION}:${CLOUD_PROVIDER}:default" $PCF_RELEASE_NOTES)
  if [ ${cnt} -gt 0 ]; then 
    PCF_OPSMAN_VERS=$(egrep "^${PCF_VERSION}:${CLOUD_PROVIDER}:default" $PCF_RELEASE_NOTES | awk -F: '{ print $4 }' | head -1)
    PCF_OPSMAN_TYPE=$(echo "${PCF_OPSMAN_VERS}" | awk -F'.' '{ printf("%s.%s\n",$1,$2 )}')
    PCF_STEMCELL_TYPE=$(egrep "^${PCF_VERSION}:${CLOUD_PROVIDER}:default" $PCF_RELEASE_NOTES | awk -F: '{ print $6 }' | head -1)
    PCF_STEMCELL_VERS=$(egrep "^${PCF_VERSION}:${CLOUD_PROVIDER}:default" $PCF_RELEASE_NOTES | awk -F: '{ print $7 }' | head -1)
    PCF_DEFAULT_TEMPLATE=$(egrep "^${PCF_VERSION}:${CLOUD_PROVIDER}:default" $PCF_RELEASE_NOTES | awk -F: '{ print $8 }')

    if [ "${PCF_DEFAULT_TEMPLATE}" == "" -o "${PCF_DEFAULT_TEMPLATE}" == "-" ]; then 
      echo "ERROR: There is currently no tested release for $PRODUCT_TILE_NAME $PCF_VERSION on $CLOUD_PROVIDER"; exit
    fi
  else
    echo "ERROR: $PRODUCT_TILE_NAME Release $PCF_VERSION not defined in $PCF_RELEASE_NOTES"; exit 1
  fi
else
  echo "ERROR: can not find ${PCF_RELEASE_NOTES} file"; exit 1
fi

##############################################################################################
######################################### PREPERATION ########################################
##############################################################################################

if [ "${CLOUD_PROVIDER}" == "gcp" ]; then 
  # --- VERIFY GCP SERVICE ACCOUNTS ---
  if [ ! -f "${GCP_SERVICE_ACCOUNT}" ]; then 
    cnt=$(gcloud iam service-accounts list | grep -c " pcfconfig@" | grep -v "EMAIL")
    if [ $cnt -eq 0 ]; then
      messagePrint "Creating Servivce-Account" "pcfconfig"
  
      gcloud iam service-accounts create pcfconfig --display-name="pcfconfig" 2>/dev/null
      if [ $? -ne 0 ]; then
        echo "ERROR: Creating Service account: pcfconfig failed"; exit 1
      else
        sleep 5
      fi
  
      svc=$(gcloud iam service-accounts list --filter "name:pcfconfig" | grep -v "EMAIL" | awk '{ print $(NF-1) }')
  
      gcloud iam service-accounts add-iam-policy-binding $svc \
        --member="serviceAccount:$svc" --role="roles/owner" > /dev/null 2>&1
      gcloud projects add-iam-policy-binding $GCP_PROJECT \
        --member="serviceAccount:$svc" --role="roles/owner" > /dev/null 2>&1
    fi
  
    # DELETE OLD KEYS
    svc=$(gcloud iam service-accounts list --filter "name:pcfconfig@" | grep -v "EMAIL" | head -1 | awk '{ print $(NF-1) }')
    for n in $(gcloud iam service-accounts keys list --iam-account=$svc | awk '{ print $1 }' | grep -v KEY_ID); do
      gcloud iam service-accounts keys delete --iam-account=$svc $n -q > /dev/null 2>&1
    done
  
    gcloud iam service-accounts keys create $GCP_SERVICE_ACCOUNT --iam-account=${svc} > /dev/null 2>&1
  fi
fi

##############################################################################################
######################################## MAIN PROGRAMM #######################################
##############################################################################################

# --- GENERATE TERRAFORM VARFILE (terraform.tfvars) ---
OPSMAN_RELEASE_NOTES=${PCFCONFIG_PATH}/files/opsman-release-notes.txt
TF_VARFILE="/tmp/terraform_${CLOUD_PROVIDER}.tfvars"; rm -f $TF_VARFILE; touch $TF_VARFILE

# --- REGION FIX ---
if [ "${CLOUD_PROVIDER}" == "gcp" ]; then 
  cnt=$(echo "$GCP_REGION" | grep -c "europe")
  if [ $cnt -gt 0 ]; then SEARCH_REG="eu"; fi
  cnt=$(echo "$GCP_REGION" | grep -c "asia")
  if [ $cnt -gt 0 ]; then SEARCH_REG="asia"; fi
  cnt=$(echo "$GCP_REGION" | egrep -c "northamerica|us")
  if [ $cnt -gt 0 ]; then SEARCH_REG="us"; fi
fi

if [ "${CLOUD_PROVIDER}" == "aws" ]; then 
  SEARCH_REG="$AWS_REGION"
fi 

if [ "${CLOUD_PROVIDER}" == "azure" ]; then 
  cnt=$(echo "$AZURE_LOCATION" | egrep -c "europe")
  if [ $cnt -gt 0 ]; then SEARCH_REG="west_europe"; fi
  cnt=$(echo "$AZURE_LOCATION" | egrep -c "_us")
  if [ $cnt -gt 0 ]; then SEARCH_REG="east_us"; fi
  cnt=$(echo "$AZURE_LOCATION" | egrep -c "_asia")
  if [ $cnt -gt 0 ]; then SEARCH_REG="southeast_asia"; fi
fi

cnt=$(egrep "^(${PCF_OPSMAN_VERS}|${PCF_OPSMAN_VERS}.[0-9]*)," $OPSMAN_RELEASE_NOTES | grep -c ",${CLOUD_PROVIDER},")
if [ ${cnt} -gt 0 ]; then
  # --- CHECK OPSMAN VERSION ---
  cnt=$(egrep "^(${PCF_OPSMAN_VERS}|${PCF_OPSMAN_VERS}.[0-9]*)," $OPSMAN_RELEASE_NOTES | grep -c ",${CLOUD_PROVIDER},${AWS_REGION},")
  if [ ${cnt} -gt 0 ]; then
    OPSMAN_IMAGE=$(egrep "^(${PCF_OPSMAN_VERS}|${PCF_OPSMAN_VERS}.[0-9]*)," $OPSMAN_RELEASE_NOTES | \
                 grep ",${CLOUD_PROVIDER},${AWS_REGION}," | head -1 | awk -F',' '{ print $5 }')
  else
    OPSMAN_IMAGE=$(egrep "^(${PCF_OPSMAN_VERS}|${PCF_OPSMAN_VERS}.[0-9]*)," $OPSMAN_RELEASE_NOTES | \
                 grep ",${CLOUD_PROVIDER}," | head -1 | awk -F',' '{ print $5 }')
  fi
else
  echo "ERROR: Can not find configuration for OpsManager $PCF_OPSMAN_VERS in $OPSMAN_RELEASE_NOTES"; exit 1
fi

if [ "${CLOUD_PROVIDER}" == "gcp" ]; then
  list=$($GCLOUD compute zones list | grep "${GCP_REGION}" | awk '{ print $1 }')
  GCP_AZ1=$(echo $list | awk '{ print $1 }')
  GCP_AZ2=$(echo $list | awk '{ print $2 }')
  GCP_AZ3=$(echo $list | awk '{ print $3 }')

  echo "env_name           = \"${ENV_NAME}\""                                  >> $TF_VARFILE
  echo "region             = \"${GCP_REGION}\""                                >> $TF_VARFILE
  echo "zones              = [\"${GCP_AZ1}\", \"${GCP_AZ2}\", \"${GCP_AZ3}\"]" >> $TF_VARFILE
  echo "opsman_image_url   = \"${OPSMAN_IMAGE}\""                              >> $TF_VARFILE
  echo "dns_suffix         = \"${DNS_DOMAIN}\""                                >> $TF_VARFILE
  echo "project            = \"${GCP_PROJECT}\""                               >> $TF_VARFILE
  echo ""                                                                      >> $TF_VARFILE
  echo "ssl_cert = <<SSL_CERT"                                                 >> $TF_VARFILE
  echo "SSL_CERT"                                                              >> $TF_VARFILE
  echo ""                                                                      >> $TF_VARFILE
  echo "ssl_private_key = <<SSL_KEY"                                           >> $TF_VARFILE
  echo "SSL_KEY"                                                               >> $TF_VARFILE

  if [ -f $GCP_SERVICE_ACCOUNT ]; then
    PRJ=$(cat $GCP_SERVICE_ACCOUNT | jq -r '.project_id')
    if [ "${PRJ}" == "$GCP_PROJECT" ]; then 
      echo "service_account_key = <<SERVICE_ACCOUNT_KEY"     >> $TF_VARFILE
      cat $GCP_SERVICE_ACCOUNT                               >> $TF_VARFILE
      echo "SERVICE_ACCOUNT_KEY"                             >> $TF_VARFILE
    else
      echo "ERROR: Project-Id ($PRJ) in Service Account ($GCP_SERVICE_ACCOUNT) does not match with"
      echo "       whith the Service Account provided with the option --gcp-service-account $GCP_PROJECT"
      exit 1
    fi
  else
    echo "ERROR: Service Account File ($GCP_SERVICE_ACCOUNT) could not be found"; exit
  fi

fi

if [ "${CLOUD_PROVIDER}" == "aws" ]; then
  # --- GET AVAILABILITY ZONE FOR LOCATION ---
  AWS_AZ1=$(aws ec2 describe-availability-zones --region $AWS_REGION | jq -r '.AvailabilityZones[0].ZoneName')
  AWS_AZ2=$(aws ec2 describe-availability-zones --region $AWS_REGION | jq -r '.AvailabilityZones[1].ZoneName')
  AWS_AZ3=$(aws ec2 describe-availability-zones --region $AWS_REGION | jq -r '.AvailabilityZones[2].ZoneName')

  echo "env_name           = \"${ENV_NAME}\""                                  >> $TF_VARFILE
  echo "access_key         = \"${AWS_ACCESS_KEY}\""                            >> $TF_VARFILE
  echo "secret_key         = \"${AWS_SECRET_KEY}\""                            >> $TF_VARFILE
  echo "region             = \"${AWS_REGION}\""                                >> $TF_VARFILE
  echo "availability_zones = [\"${AWS_AZ1}\", \"${AWS_AZ2}\", \"${AWS_AZ3}\"]" >> $TF_VARFILE
  echo "ops_manager_ami    = \"${OPSMAN_IMAGE}\""                              >> $TF_VARFILE
  echo "dns_suffix         = \"${DNS_DOMAIN}\""                                >> $TF_VARFILE
  echo ""                                                                      >> $TF_VARFILE
  echo "ssl_cert = <<SSL_CERT"                                                 >> $TF_VARFILE
  echo "SSL_CERT"                                                              >> $TF_VARFILE
  echo ""                                                                      >> $TF_VARFILE
  echo "ssl_private_key = <<SSL_KEY"                                           >> $TF_VARFILE
  echo "SSL_KEY"                                                               >> $TF_VARFILE
fi

if [ "${CLOUD_PROVIDER}" == "azure" ]; then 
  echo "subscription_id       = \"${AZURE_SUBSCRIPTION_ID}\""                  >> $TF_VARFILE
  echo "tenant_id             = \"${AZURE_TENANT_ID}\""                        >> $TF_VARFILE
  echo "client_id             = \"${AZURE_CLIENT_ID}\""                        >> $TF_VARFILE
  echo "client_secret         = \"${AZURE_CLIENT_SECRET}\""                    >> $TF_VARFILE
  echo ""                                                                      >> $TF_VARFILE
  echo "env_name              = \"${ENV_NAME}\""                               >> $TF_VARFILE
  echo "env_short_name        = \"${PRODUCT_TILE}\""                           >> $TF_VARFILE
  echo "location              = \"${AZURE_LOCATION}\""                         >> $TF_VARFILE
  echo "ops_manager_image_uri = \"${OPSMAN_IMAGE}\""                           >> $TF_VARFILE
  echo "dns_suffix            = \"${DNS_DOMAIN}\""                             >> $TF_VARFILE
  echo "vm_admin_username     = \"opsman\""                                    >> $TF_VARFILE
fi

TERRAFORM_RELEASE_NOTES=${PCFCONFIG_PATH}/files/terraform-release-notes.txt
PCF_LATEST=$(egrep ":${PCF_OPSMAN_TYPE}" $TERRAFORM_RELEASE_NOTES | awk -F: '{ print $2 }' | head -1) 
PCFCONFIG_TF_STATE="${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/terraforming-${PRODUCT_TILE}/.pcfconfig-terraform"
PCFCONFIG_OPSMAN_STATE="${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/terraforming-${PRODUCT_TILE}/.pcfconfig-opsman"
PCFCONFIG_PKS_STATE="${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/terraforming-${PRODUCT_TILE}/.pcfconfig-pks"
PCFCONFIG_PAS_STATE="${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/terraforming-${PRODUCT_TILE}/.pcfconfig-pas"
PCFCONFIG_PKS_AUTH_STATE="${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/terraforming-${PRODUCT_TILE}/.pcfconfig-pks-setup"

# --- INITIALIZE STATE FILES ---
#touch $PCFCONFIG_TF_STATE $PCFCONFIG_OPSMAN_STATE $PCFCONFIG_PKS_STATE $PCFCONFIG_PAS_STATE

# --- ONLY EXECUTE IF STATUS OF LAST RUNN IS NOT 'completed' ---
if [ "$(getPCFconfigState $PCFCONFIG_TF_STATE)" != "completed" ]; then 
  setPCFconfigState $PCFCONFIG_TF_STATE "started"

  ${PCFCONFIG_PATH}/pcfconfig-terraform --pivnet-token $PIVNET_TOKEN \
                                        $TF_TILE_OPTION $TF_VARFILE \
                                        --deployment $CLOUD_PROVIDER \
                                        --cf-version $PCF_LATEST \
                                        --directory-prefix cf-terraform \
                                        --install-mode delete --no-ask \
                                        --aws-route53 $ROUTE53_TOKEN
  if [ $? -ne 0 ]; then 
    setPCFconfigState $PCFCONFIG_TF_STATE "failed"
    echo "ERROR: Problem with pcfconfig-terraform occured"; exit 1
    exit 1
  fi

  cd ${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/terraforming-${PRODUCT_TILE}

  #cp /Users/sadubois/workspace/terraform/ops_manager.tf ${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/modules/ops_manager

  echo "--------------------------------------- TERRAFORM DEPLOYMENT ----------------------------------------------"
  terraform init > /tmp/$$_log 2>&1
  terraform plan -out=plan >> /tmp/$$_log 2>&1
  terraform apply -auto-approve >> /tmp/$$_log 2>&1; ret=$?
  tail -20 /tmp/$$_log
  echo "-----------------------------------------------------------------------------------------------------------"
  if [ $ret -ne 0 ]; then
    echo "ERROR: Problem with teraform apply"
    setPCFconfigState $PCFCONFIG_TF_STATE "failed"
    exit 1
  else
    setPCFconfigState $PCFCONFIG_TF_STATE "completed"
  fi
else
  messagePrint "pcfconfig-terraform already done" "skipping"
fi

# --- ONLY EXECUTE IF STATUS OF LAST RUNN IS NOT 'completed' ---
if [ "$(getPCFconfigState $PCFCONFIG_OPSMAN_STATE)" != "completed" ]; then 
  cd ${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/terraforming-${PRODUCT_TILE}

  setPCFconfigState $PCFCONFIG_OPSMAN_STATE "started"
  pcfconfig-opsman -u $OPSMAN_USER -p $OPSMAN_PASS -dp $OPSMAN_DKEY --aws-route53 $ROUTE53_TOKEN 

  if [ $? -ne 0 ]; then
    setPCFconfigState $PCFCONFIG_OPSMAN_STATE "failed"
    echo "ERROR: Problem with pcfconfig-opsman occured"; exit 1
  else
    setPCFconfigState $PCFCONFIG_OPSMAN_STATE "completed"
  fi
else
  messagePrint "pcfconfig-opsman already done" "skipping"
fi

if [ "${PRODUCT_TILE}" == "pks" ]; then
  # --- ONLY EXECUTE IF STATUS OF LAST RUNN IS NOT 'completed' ---
  if [ "$(getPCFconfigState $PCFCONFIG_PKS_STATE)" != "completed" ]; then 
    cd ${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/terraforming-${PRODUCT_TILE}
  
    setPCFconfigState $PCFCONFIG_PKS_STATE "started"
    pcfconfig-pks -u $OPSMAN_USER  -p $OPSMAN_PASS --pivnet-token "$PIVNET_TOKEN" \
      --pks-version $PKS_VERSION --aws-route53 $ROUTE53_TOKEN
  
    if [ $? -ne 0 ]; then
      setPCFconfigState $PCFCONFIG_PKS_STATE "failed"
      echo "ERROR: Problem with pcfconfig-pks occured"; exit 1
    else
      setPCFconfigState $PCFCONFIG_PKS_STATE "completed"
    fi
  else
    messagePrint "pcfconfig-pks already done" "skipping"
  fi

  # --- ONLY EXECUTE IF STATUS OF LAST RUNN IS NOT 'completed' ---
  if [ "$(getPCFconfigState $PCFCONFIG_PKS_AUTH_STATE)" != "completed" ]; then 
    cd ${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/terraforming-${PRODUCT_TILE}
  
    setPCFconfigState $PCFCONFIG_PKS_AUTH_STATE "started"
    pcfconfig-pks-setup --pks-admin-user $PKS_ADMIN_USER --pks-admin-pass $PKS_ADMIN_PASS \
         --pks-admin-mail $PKS_ADMIN_MAIL --aws-route53 $ROUTE53_TOKEN \
         --pks-cluster-1-name $PKS_CLUSTER_1_NAME \
         --pks-cluster-1-plan $PKS_CLUSTER_1_PLAN \
         --pks-cluster-2-name $PKS_CLUSTER_2_NAME \
         --pks-cluster-2-plan $PKS_CLUSTER_2_PLAN \
         --pks-cluster-3-name $PKS_CLUSTER_3_NAME \
         --pks-cluster-3-plan $PKS_CLUSTER_3_PLAN 

    if [ $? -ne 0 ]; then
      setPCFconfigState $PCFCONFIG_PKS_AUTH_STATE "failed"
      echo "ERROR: Problem with pcfconfig-pks-setup occured"; exit 1
    else
      setPCFconfigState $PCFCONFIG_PKS_AUTH_STATE "completed"
    fi
  else
    messagePrint "pcfconfig-pks-setup already done" "skipping"
  fi
else
  # --- ONLY EXECUTE IF STATUS OF LAST RUNN IS NOT 'completed' ---
  if [ "$(getPCFconfigState $PCFCONFIG_PAS_STATE)" != "completed" ]; then
    cd ${TF_WORKDIR}/cf-terraform-${CLOUD_PROVIDER}/terraforming-${PRODUCT_TILE}

    setPCFconfigState $PCFCONFIG_PAS_STATE "started"
    pcfconfig-pas -u $OPSMAN_USER  -p $OPSMAN_PASS --pivnet-token "$PIVNET_TOKEN" \
      --pas-version $PAS_VERSION --aws-route53 $ROUTE53_TOKEN $PAS_SRT

    if [ $? -ne 0 ]; then
      setPCFconfigState $PCFCONFIG_PAS_STATE "failed"
      echo "ERROR: Problem with pcfconfig-pas occured"; exit 1
    else
      setPCFconfigState $PCFCONFIG_PAS_STATE "completed"
    fi
  else
    messagePrint "pcfconfig-pas already done" "skipping"
  fi
fi









